spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro_codeando
    password:
    username: root
    #Jpa-Hibernate
  jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
      hibernate:
        ddl-auto: create-drop

jwt:
  expired: 1440000
  secret-key: developeando404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970